server:
  port: 8080
spring:
  application:
    name: task_system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mini_task_management_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      # 本地虚拟机配置
      host: 172.30.138.31
      port: 6379
      password: 123456
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.github.zephyrtoria.task_system.domain # 别名扫描包
logging:
  level:
    com.github.zephyrtoria.task_system.domain: debug

knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false